# Patchwork - automated patch tracking system
# Copyright (C) 2026 Robin Jarry <robin@jarry.cc>
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Generic utilities for mailing-list synchronization.
"""

import email
import io
import logging
import mailbox
import os
import re

from django.conf import settings
from django.core.mail import get_connection
from django.db import transaction

from patchwork.models import Cover
from patchwork.models import Patch
from patchwork.models import Series
from patchwork.models import SeriesMetadata
from patchwork.parser import DuplicateMailError
from patchwork.parser import clean_header
from patchwork.parser import parse_mail

logger = logging.getLogger(__name__)

HTML_COMMENT_RE = re.compile(r'(?s)<!--.*?-->')

AI_SECTION_HEADERS = [
    'summary by coderabbit',
    'summary by copilot',
    'walkthrough',
    'generated by',
]


def sanitize_pr_body(body):
    """
    Strip HTML comments and AI-generated sections from a pull request body
    before using it as a cover letter description.
    """
    if not body:
        return ''
    body = HTML_COMMENT_RE.sub('', body)
    lines = body.split('\n')
    result = []
    skip = False
    for line in lines:
        lower = line.strip().lower()
        if lower.startswith('#'):
            heading = lower.lstrip('# ')
            for marker in AI_SECTION_HEADERS:
                if heading.startswith(marker):
                    skip = True
                    break
            if skip:
                continue
            skip = False
        if not skip:
            result.append(line)
    return '\n'.join(result).strip()


def sender_identity(user, forge_config):
    """
    Return a (name, email) tuple for a forge user. Falls back to the project's
    sender_email when the user has no public email address.
    """
    name = user.name or user.login
    if user.email:
        addr = user.email
    else:
        addr = email.utils.parseaddr(forge_config.sender_email)[1]
        name += ' (via Patchwork)'
    return name, addr


def find_series_by_pr(backend, forge_config, pr_number):
    """
    Find all series linked to a pull request via SeriesMetadata,
    ordered by most recent first.
    """
    return (
        Series.objects.filter(
            project=forge_config.project,
            metadata__key=backend.meta_key_pr(),
            metadata__value=backend.pr_ref(forge_config, pr_number),
        )
        .select_related('cover_letter')
        .order_by('version')
    )


def reply_to_msgid(series):
    """
    Return the message-id to use as In-Reply-To when sending replies to a
    series. Prefers the cover letter, falls back to first patch.
    """
    if series.cover_letter:
        return series.cover_letter.msgid
    patches = list(series.patches.order_by('number')[:1])
    if patches:
        return patches[0].msgid
    return ''


def next_version(backend, forge_config, event):
    """
    Determine the version number and threading info for a respin.

    Returns (version, in_reply_to, previous_ref) where version is the next
    version number, in_reply_to is the message-id of the original series cover
    letter, and previous_ref is the previous HEAD SHA for range-diff
    generation.
    """
    series = find_series_by_pr(backend, forge_config, event.pr_number)
    first = series.first()
    last = series.last()

    if not first or not last:
        return 1, '', ''

    return last.version + 1, reply_to_msgid(first), event.pr_before


def bytes_to_mbox(buf):
    """
    Create a mailbox.mbox object from bytes.
    """
    # The builtin constructor only accepts file paths. Trick it by passing
    # /dev/null and replace the opened file with BytesIO.
    mbox = mailbox.mbox(os.devnull, create=False)
    mbox._file.close()
    mbox._file = io.BytesIO(buf)
    return mbox


@transaction.atomic
def ingest_emails(mbox, backend, forge_config, event):
    """
    Parse raw emails from a mailbox.mbox and create Series/Patch/Cover objects
    in the database via parse_mail(). After ingestion, store forge metadata on
    the series using backend.series_metadata().
    """
    list_id = forge_config.project.listid
    series = None

    for msg in mbox:
        try:
            result = parse_mail(msg, list_id, ignore_hints=True)
        except DuplicateMailError:
            logger.warning(
                'patch already ingested: %s: %s',
                clean_header(msg.get('Message-ID')),
                clean_header(msg.get('Subject')),
            )
            continue
        except ValueError:
            logger.exception(
                'failed to ingest patch: %s: %s',
                clean_header(msg.get('Message-ID')),
                clean_header(msg.get('Subject')),
            )
            continue

        if isinstance(result, (Cover, Patch)):
            series = result.series

    if series:
        metadata = backend.series_metadata(forge_config, event)
        for key, value in metadata.items():
            if value:
                SeriesMetadata.objects.update_or_create(
                    series=series,
                    key=key,
                    defaults={'value': value},
                )


def _msg_header_addresses(msg, *headers):
    values = []
    for h in headers:
        for v in msg.get_all(h, []):
            txt = clean_header(v)
            if txt:
                values.append(txt)

    addrs = set()
    for _, addr in email.utils.getaddresses(values):
        addrs.add(addr)
    return list(addrs)


def send_emails(mbox, forge_config):
    """
    Send raw emails from a mailbox.mbox via SMTP. Reads Sender, From, To and Cc
    addresses from the email headers.
    """
    with get_connection(fail_silently=False) as conn:
        for key, msg in mbox.iteritems():
            senders = _msg_header_addresses(msg, 'sender')
            recipients = _msg_header_addresses(msg, 'from', 'to', 'cc')
            logger.info(
                'sending patch: %s -> %s: %s',
                ','.join(senders),
                ','.join(recipients),
                clean_header(msg.get('subject', '')),
            )
            # XXX: only works if email backend is smtp
            errs = conn.connection.sendmail(
                senders[0], recipients, mbox.get_bytes(key)
            )
            for rcpt, err in errs.items():
                logger.warning('send patch to %s failed: %s', rcpt, err)


TRAILER_RE = re.compile(
    r'^(Signed-off-by|Acked-by|Reviewed-by|Tested-by|Reported-by'
    r'|Suggested-by|Co-authored-by|Cc):.*$',
    re.MULTILINE,
)

COMMENT_MARKER = '<!-- patchwork -->'


def forge_branch_name(series):
    """
    Generate a branch name for a series on the forge.

    Format: {prefix}/{hex_id}/{slug}
    """
    name = series.name or ''
    slug = re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')
    if len(slug) > 50:
        slug = slug[:50].rstrip('-')
    return f'{settings.FORGE_BRANCH_PREFIX}/{series.id:x}/{slug}'


def build_pr_body(series):
    """
    Build a pull request body from a series cover letter or first patch.

    Strips git trailers and appends a patchwork link and loop
    prevention marker.
    """
    if series.cover_letter and series.cover_letter.content:
        body = series.cover_letter.content.strip()
    else:
        patches = list(series.patches.order_by('number')[:1])
        if patches and patches[0].content:
            body = patches[0].content.strip()
        else:
            body = ''

    body = TRAILER_RE.sub('', body).strip()
    body += f'\n\n{COMMENT_MARKER}'
    return body


def series_from_forge(series):
    """
    Return True if the series originated from a forge sync.

    Checks for X-Patchwork-Hint: ignore in patch headers, which is
    added by format_patches() when sending forge PRs to the mailing
    list.
    """
    for patch in series.patches.all()[:1]:
        if not patch.headers:
            continue
        parsed = email.message_from_string(patch.headers)
        hint = parsed.get('X-Patchwork-Hint', '')
        if hint.lower() == 'ignore':
            return True
    return False
