# Generated by Django 5.1.15 on 2026-05-25 02:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0048_series_dependencies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'url',
                    models.URLField(
                        help_text='The URL to send webhook payloads to.',
                        max_length=500,
                    ),
                ),
                (
                    'secret',
                    models.CharField(
                        blank=True,
                        default='',
                        help_text='Secret used to sign webhook payloads via HMAC-SHA256.',
                        max_length=255,
                    ),
                ),
                (
                    'events',
                    models.CharField(
                        default='*',
                        help_text='Comma-separated list of event categories, or * for all.',
                        max_length=500,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                (
                    'created',
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='webhooks',
                        to='patchwork.project',
                    ),
                ),
            ],
            options={
                'unique_together': {('project', 'url')},
            },
        ),
    ]
