# Generated by Django 5.1.15 on 2026-05-30 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0049_series_respin_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesMetadata',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.TextField(db_index=True, max_length=255)),
                (
                    'series',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='metadata',
                        to='patchwork.series',
                    ),
                ),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('series', 'key')},
            },
        ),
    ]
