# Generated by Django 5.1.15 on 2026-05-30 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('patchwork', '0050_series_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgeConfig',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('backend', models.CharField(max_length=50)),
                ('repo', models.CharField(max_length=255)),
                ('from_email', models.CharField(default='', max_length=255)),
                ('sync_ml_to_forge', models.BooleanField(default=True)),
                ('sync_forge_to_ml', models.BooleanField(default=True)),
                ('thread_respins', models.BooleanField(default=False)),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='forges',
                        to='patchwork.project',
                    ),
                ),
            ],
            options={
                'verbose_name': 'forge configuration',
                'verbose_name_plural': 'forge configurations',
                'unique_together': {('project', 'backend')},
            },
        ),
    ]
